name: ngerti
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  uuid: ^3.0.5
  http: ^0.13.4
  just_audio: ^0.9.18
  firebase_core: ^1.10.6
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.5
  flutter_native_splash: ^1.3.2
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_native_splash:
  color: "#2d3436"
  image: images/icon.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"

flutter:

  uses-material-design: true

  assets:
    - images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
